apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralretail-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: neuralretail

  template:
    metadata:
      labels:
        app: neuralretail

    spec:
      containers:
      - name: neuralretail
        image: neuralretail:latest

        ports:
        - containerPort: 8501