apiVersion: v1
kind: Service
metadata:
  name: neuralretail-service

spec:
  selector:
    app: neuralretail

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501

  type: LoadBalancer